openshift/aws-load-balancer-operator

Makefile, hack/verify-deps.sh, hack/verify-generated.sh, hack/verify-gofmt.sh
Added scripts which verify that the generated code/configuration in the commit is up-to-date with the backing code.
=> Add verify scripts for generated logic

Dockerfile, Makefile, assets/iam-policy.json, bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, cmd/iamctl/LICENSE, cmd/iamctl/ast.go, cmd/iamctl/const.go, cmd/iamctl/main.go, cmd/iamctl/minify.go, cmd/iamctl/policy.go, config/rbac/role.yaml, docs/iamctl/iamctl.md, docs/iamctl/iamctl_genpolicy.md, go.mod, go.sum, main.go, pkg/controllers/awsloadbalancercontroller/controller.go, pkg/controllers/awsloadbalancercontroller/credentials_request.go, pkg/controllers/awsloadbalancercontroller/credentials_request_test.go, pkg/controllers/awsloadbalancercontroller/credentialsrequest.go, pkg/controllers/awsloadbalancercontroller/iam_policy.go, pkg/controllers/awsloadbalancercontroller/subnettagging_test.go, pkg/controllers/utils/test/events.go, pkg/controllers/utils/test/vars.go, vendor/golang.org/x/net/http2/go118.go, vendor/golang.org/x/net/http2/not_go118.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/term/codereview.cfg, vendor/golang.org/x/term/term.go, vendor/modules.txt
Ref: [CFE-314](https://issues.redhat.com/browse/CFE-314)
=> Add reconciliation for Credential Requests

pkg/controllers/awsloadbalancercontroller/controller.go, pkg/controllers/awsloadbalancercontroller/service.go, pkg/controllers/awsloadbalancercontroller/service_test.go, pkg/controllers/awsloadbalancercontroller/webhooks.go
The controller needs a service to register a validating and mutating webhook for `Ingress`, `IngressGroup` and `IngressClass` resources.
/assign @alebedev87 @thejasn
=> Add functionality to ensure service for controller

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/rbac/role.yaml, go.mod, go.sum, hack/operator-credentials-request.yaml, pkg/controllers/awsloadbalancercontroller/controller.go, pkg/controllers/awsloadbalancercontroller/credentials_request.go, pkg/controllers/awsloadbalancercontroller/credentials_request_test.go, pkg/controllers/awsloadbalancercontroller/ingressclass_test.go, pkg/controllers/awsloadbalancercontroller/rbac.go, pkg/controllers/awsloadbalancercontroller/rbac_clusterrole.go, pkg/controllers/awsloadbalancercontroller/rbac_clusterrolebinding.go, pkg/controllers/awsloadbalancercontroller/rbac_role.go, pkg/controllers/awsloadbalancercontroller/rbac_rolebinding.go, pkg/controllers/awsloadbalancercontroller/rbac_rules.go, pkg/controllers/awsloadbalancercontroller/rbac_test.go, pkg/controllers/awsloadbalancercontroller/service_test.go, pkg/controllers/awsloadbalancercontroller/serviceaccount.go, pkg/controllers/awsloadbalancercontroller/serviceaccount_test.go, pkg/controllers/awsloadbalancercontroller/subnettagging_test.go, pkg/controllers/utils/test/events.go, pkg/controllers/utils/test/vars.go, vendor/modules.txt, vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
RFE: [CFE-316](https://issues.redhat.com/browse/CFE-316)
=> Added ensure funcs for serviceaccounts and clusterroles 

pkg/controllers/awsloadbalancercontroller/rbac_rules.go
Fix typo between get and list actions.
=> Fix RBAC rules

main.go, pkg/aws/aws.go, pkg/aws/aws_test.go, pkg/controllers/awsloadbalancercontroller/controller.go, pkg/controllers/awsloadbalancercontroller/deployment.go, pkg/controllers/awsloadbalancercontroller/deployment_test.go
The AWS client requires a default AWS region to be specified. Added functionality to ensure this environment varible is always present in the deployment.
=> Added AWS_DEFAULT_REGION environment variable

pkg/controllers/awsloadbalancercontroller/controller.go, pkg/controllers/awsloadbalancercontroller/credentials_request.go, pkg/controllers/awsloadbalancercontroller/credentials_request_test.go, pkg/controllers/awsloadbalancercontroller/deployment.go, pkg/controllers/awsloadbalancercontroller/deployment_test.go
Return the secret which is referenced in the `CredentialsRequest` from the ensure function. Pass this to the ensure function for the deployment so that the secret can be mounted in the pod.
=> Mount AWS credentials from CredentialsRequest

pkg/controllers/awsloadbalancercontroller/controller.go, pkg/controllers/awsloadbalancercontroller/credentials_request.go, pkg/controllers/awsloadbalancercontroller/rbac_clusterrole.go, pkg/controllers/awsloadbalancercontroller/rbac_clusterrolebinding.go, pkg/controllers/awsloadbalancercontroller/rbac_role.go, pkg/controllers/awsloadbalancercontroller/rbac_rolebinding.go, pkg/controllers/awsloadbalancercontroller/rbac_test.go, pkg/controllers/awsloadbalancercontroller/serviceaccount.go, pkg/controllers/awsloadbalancercontroller/serviceaccount_test.go
=> Refactored resource names

pkg/controllers/awsloadbalancercontroller/subnettagging.go
Some clusters may be installed in multiple subnets which cannot be returned in a single `DescribeSubnets` call. So a paginator should be used which paginates over the results.
=> Paginate through cluster subnets

main.go, pkg/controllers/awsloadbalancercontroller/controller.go, pkg/controllers/awsloadbalancercontroller/credentials_request.go, pkg/controllers/awsloadbalancercontroller/credentials_request_test.go, pkg/controllers/awsloadbalancercontroller/ingressclass.go, pkg/controllers/awsloadbalancercontroller/ingressclass_test.go, pkg/controllers/awsloadbalancercontroller/serviceaccount.go, pkg/controllers/awsloadbalancercontroller/serviceaccount_test.go, pkg/controllers/awsloadbalancercontroller/status.go, pkg/controllers/awsloadbalancercontroller/status_test.go, pkg/controllers/awsloadbalancercontroller/subnettagging.go, pkg/controllers/awsloadbalancercontroller/subnettagging_test.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go, vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/modules.txt
Added improvements to the status updates so that the controller resource is reloaded after every status update. Also added conditions to the status to indicate the state of the deployment and the credentials request associated with the controller.
=> Status improvements and conditions

api/v1alpha1/awsloadbalancercontroller_types.go, bundle/manifests/networking.olm.openshift.io_awsloadbalancercontrollers.yaml, config/crd/bases/networking.olm.openshift.io_awsloadbalancercontrollers.yaml, docs/tutorial.md
Added a doc with explaination for the various fields in the controller spec.
=> Added a tutorial for the operator

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manifests/bases/aws-load-balancer-operator.clusterserviceversion.yaml
=> Added support for OwnNamespace

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
Fixes: Not being able to override `RELATED_IMAGE_CONTROLLER`
=> Fixes image args overriding

pkg/controllers/awsloadbalancercontroller/deployment.go, pkg/controllers/awsloadbalancercontroller/deployment_test.go
The controller is currently running with the default container security context. This change set the field `runAsNonRoot` to _true_ and the fields `privileged` and `allowPrivilegeEscalation` to _false_. It also sets the secomp profile to the default and drops all capabilities.
=> Bug 2086450: Explicity set the security context for the controller

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manifests/bases/aws-load-balancer-operator.clusterserviceversion.yaml, hack/operator-credentials-request.yaml
=> Fix credentialsrequest: installation docs

test/e2e/operator_test.go, test/e2e/util.go
This PR aims at helping to avoid this error:
```
operator_test.go:425: failed to create aws wafv2 acl due to operation error WAFV2: CreateWebACL, https response error StatusCode: 400, RequestID: c243bb08-448e-46ce-9d1f-0852bb1c6de6, WAFDuplicateItemException: AWS WAF couldn’t perform the operation because some resource in your request is a duplicate of an existing one.
```
If a duplicate Web ACL did appear for some reason, we need to skip the creation so that the deletion is triggered as a deferred function.
=> e2e: check web acl exists

README.md, docs/tutorial.md, test/e2e/aws.go, test/e2e/operator_test.go, test/e2e/util.go
This PR adapts the existing e2e tests for t[he new CI job](https://github.com/openshift/release/pull/36655) which runs on a ROSA STS cluster.
=> NE-1225: adapt e2e tests to enable ROSA platform with STS service

README.md, docs/versioning.md
This PR:
- Documents the versioning model, repository branch organization, OLM channels, OpenShift compatibility, and support model.
- Aims to guide users on selecting the appropriate ALBO version for their OpenShift environment.
=> OCPBUGS-36641: Add versioning and branching documentation

OWNERS
Andy is not in NID team anymore. Ryan O'Hara joined NID team.
=> OWNERS: remove old and add new member of NID team

Containerfile.aws-load-balancer-operator-bundle, bundle-hack/update_bundle.sh, drift-cache/bundle.Dockerfile
Adding the Albo Containerfile-bundle and also
created an empty update_bundle.sh for now
=> NE-2063: Add Albo Containerfile bundle and update_bundle
