openshift/aws-load-balancer-operator

Makefile
The envtest requires certain binaries which are downloaded to a cache directory. In the CI environment this directory is not writeable. Instead the envtest can be instructed to use a directory within the repository where other binaries are also present.
=> Explicitly ensure the envtest assets directory

Makefile, bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, hack/verify-bundle.sh
Added a script which verifies that the currently committed head is up-to-date. Also added this script to the `verify` target.
Also added a make target which installs the `operator-sdk` locally. And changed the environment variable name `$VERSION` to `$BUNDLE_VERSION` because it collides with the same environment variable in the build container.
=> Add verify bundle functions

Makefile, bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, bundle/manifests/elbv2.k8s.aws_ingressclassparams.yaml, bundle/manifests/elbv2.k8s.aws_targetgroupbindings.yaml, config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml, config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml, config/crd/kustomization.yaml, config/samples/ingressclassparams.yaml, config/samples/kustomization.yaml, config/samples/targetgroupbindings-v1alpha1.yaml, config/samples/targetgroupbindings-v1beta1.yaml, hack/sync-upstream-crds.sh
The operator CSV now declares the upstream CRDs as its own and are included in the bundle contests. Also added a script to update manifests from upstream.
=> Add upstream CRDs to manifests

api/v1alpha1/awsloadbalancercontroller_types.go, bundle/manifests/networking.olm.openshift.io_awsloadbalancercontrollers.yaml, config/crd/bases/networking.olm.openshift.io_awsloadbalancercontrollers.yaml, main.go, pkg/controllers/awsloadbalancercontroller/controller.go, pkg/controllers/awsloadbalancercontroller/ingressclass.go, pkg/controllers/awsloadbalancercontroller/ingressclass_test.go, pkg/controllers/awsloadbalancercontroller/status.go, pkg/controllers/awsloadbalancercontroller/subnettagging_test.go
The default `IngressClass` for the controller should be ensured by the operator. The OpenShift router reconciles all Ingress resources whose `IngressClass` is undefined. It does not reconcile only those _Ingress_ resources whose `IngressClass` is defined and the controller does not match it's own controller value. So the `IngressClass` must be instantiated to prevent the router and the controller from attempting to reconcile the same Ingress.
=> Add function to ensure default IngressClass

pkg/controllers/awsloadbalancercontroller/credentials_request.go, pkg/controllers/awsloadbalancercontroller/credentials_request_test.go
Fixes 
```
message: 'failed to grant creds: error syncing creds in mint-mode: Secret "aws-load-balancer-controller-credentialsRequest-cluster"
is invalid: metadata.name: Invalid value: "aws-load-balancer-controller-credentialsRequest-cluster":
a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters,
''-'' or ''.'', and must start and end with an alphanumeric character (e.g.
''example.com'', regex used for validation is ''[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'')'
```
=> Fixes naming issue in credentials request

.golangci.yaml
This change enables the gosec linter but disables the rule for hardcoded credentials which yields many false positives.
=> Enable gosec linter

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/rbac/upstream_role.yaml
The operand image can be passed as a parameter to the operator. This change adds the image as a environment variable which is copied to the CLI.
=> Parameterize the operand image

pkg/controllers/awsloadbalancercontroller/credentials_request.go, pkg/controllers/awsloadbalancercontroller/deployment.go, pkg/controllers/awsloadbalancercontroller/deployment_test.go, pkg/controllers/awsloadbalancercontroller/ingressclass.go, pkg/controllers/awsloadbalancercontroller/service.go, pkg/controllers/awsloadbalancercontroller/webhooks.go
Changes to the operand resources are only reconciled through the owning resource if the owning resource is marked as the controller. So instead of setting the `AWSLoadBalancerController` as just an owner the controller field should also be set to true.
Reference: https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.2/pkg/builder#Builder.Owns
=> Set the AWSLoadBalancerController as the controller resource

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, main.go, pkg/controllers/awsloadbalancercontroller/controller.go, pkg/controllers/awsloadbalancercontroller/rbac_rules.go
The namespace which is targetted by the `OperatorGroup` of the operator install configuration is passed to the deployment in the operator CSV through the annotation `olm.targetNamespaces`. The deployment can use this to watch and modify resources in only that namespace.
Correspondingly the permissions for the namespaced resources can be restricted to only that namespace.
[OperatorGroup CSV Annotations](https://docs.openshift.com/container-platform/4.10/operators/understanding/olm/olm-understanding-operatorgroups.html#olm-operatorgroups-csv-annotations_olm-understanding-operatorgroups)
=> Leverage OperatorGroup configuration for permissions

config/manager/manager.yaml, config/manifests/kustomization.yaml
The `olm.targetNamespaces` annotation is only present on the pod when the deployment is created by the OLM. So when deploying the operator the `TARGET_NAMESPACE` should default to the operator namespace and when deployed through an operator bundle should be taken from the annotation.
=> Patch the target namespace annotation only for the bundle

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manifests/bases/aws-load-balancer-operator.clusterserviceversion.yaml
The _ClusterServiceVersion_'s `description` field is displayed in the console. These should contain instructions for installing the operator. This change adds the instructions to create the `CredentialsRequest` before installing the operator.
/assign @alebedev87 @hongkailiu
=> Bug 2080153: Added instructions to install operator in CSV

pkg/controllers/awsloadbalancercontroller/controller.go
The subnets were tagged correctly however they were written incorrectly into the status. The return values were not assigned to variables in the correct order.
/assign @thejasn
=> Fix subnets written into status

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
Explicitly set the [seccompProfile](https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads) for the operator pod and drop all [capabilities](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container) in the operator and proxy containers.
/assign @thejasn 
/label px-approved
/label docs-approved
/label qe-approved
=> Set securityContext for operator pods

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml
Fix security context of kube-proxy
---
Fixes
`
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "kube-rbac-proxy" must set securityContext.allowPrivilegeEscalation=false)
`
=> Fix security context of kube-proxy

pkg/controllers/awsloadbalancercontroller/webhooks.go, pkg/controllers/awsloadbalancercontroller/webhooks_test.go
The webhook rules also have a scope field which is defaulted to _all_("*") and this was being flagged as an update required by the
controller. So the scope is now set and the comparision of the fields on the rule is performed on each field individually. Also added tests to verify this functionality.
=> Explicity set the scopes for the webhook rules

pkg/controllers/awsloadbalancercontroller/controller.go
Updated incorrect predicate
---
Fixes incorrect usage of `WithEventFilter()`, where all objects (parent and child) were subjected to the same predicate, leading to missed events. 
=> Updated incorrect predicate

.ci-operator.yaml, Makefile, test/e2e/util.go
[Migration to golang 1.19](https://github.com/openshift/release/pull/33283) raised a couple of problems:
- `golangci-lint` of version `v1.44.2` which is currently used in `main` breaks any linting resulting in OOM due to the lack of 1.19 support introduced later (`>=v1.48.0`)
- security context which would comply with `restricted` PodSecurity (enforced in 4.12) is missing in the e2e test POD
`build_root` is added to the repository as well, to be more flexible in the future.
=> Prepapre for golang 1.19 CI config change

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manager/manager.yaml, go.mod, go.sum, main.go, vendor/modules.txt
Description
---
Bumps aws-load-balancer-controller to `v2.4.4` and the corresponding default controller image  to `quay.io/aws-load-balancer-operator/aws-load-balancer-controller:95d71cc4e7e5` (pins to https://github.com/openshift/aws-load-balancer-controller/tree/2c04703264566be3608cbbf4145929b549fe320a).
Docs and Release notes: https://github.com/openshift/openshift-docs/pull/52292, https://github.com/openshift/openshift-docs/pull/52309
=> CFE-648: Upgrade aws load balancer controller to v2.4.4

pkg/controllers/awsloadbalancercontroller/deployment.go, pkg/controllers/awsloadbalancercontroller/deployment_test.go
Description
---
In the previous release, the user was allowed to set the `target-type=ip` on `Service` and `Ingress` type resources, which is not supported on Openshift due to its dependency on AWS VPC CNI. A feature gate `EnableIPTargetType` was added to the controller to controller if `target-type=ip` is enabled. 
This PR disables IP mode for `target-type` on both `Service` and `Ingress` resources. 
Release notes: https://github.com/openshift/openshift-docs/pull/52292
=> CFE-649: Disable ip target type on Service and Ingress resources

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manager/manager.yaml, docs/install.md, docs/prerequisites.md, docs/tutorial.md
This PR adds the missing SA token to the operator's POD to enable the usage of the prerequsite secret for the OCP cluster in STS mode. Also it documents the creation of the STS secret for the operator (not operand).
No e2e test covers STS setup, manual test: https://gist.github.com/alebedev87/f7739eb775a07350e77f0724de34728f
=> OCPBUGS-3258: fix STS support for operator

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manifests/bases/aws-load-balancer-operator.clusterserviceversion.yaml
What's inside:
- ALBO is pretty much tightly bound to its default namespace: `aws-load-balancer-operator`. This PR adds this namespace as suggested which means that it'll be shown as recommended to the end user in OperatorHub UI.
- The manual instruction to create `CredentialsRequest` had a typo - `EOF` was having to many white spaces.
- Some other informational fields which will be added to OperatorHub UI.
=> CSV: add suggested namespace and fix manual step

README.md, docs/proxy.md
The operator needs a way to trust a custom CA. The cluster wide egress proxy with a "not public" certificate is one of the use cases for this. It can be achieved only by the manual intervention done by the user (cluster or namespace admin) as the operator itself makes calls to the external resources at startup (AWS endpoints to get VPC ID).
This PR adds the manual instructions which let ALBO trust a custom CA.
Manual test:
1. Replace the CA file (`/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`) with a fake CA to show that ALBO fails due to AWS golang client failure:
```
$ oc -n aws-load-balancer-operator get sub aws-load-balancer-operator -o yaml | yq .spec.config
volumeMounts:
- mountPath: /etc/pki/ca-trust/extracted/pem
name: trusted-ca-fake
volumes:
- configMap:
items:
- key: …
```
=> OCPBUGS-4052: document ALBO configuration to trust egress proxy CA

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/aws-load-balancer-operator.clusterserviceversion.yaml, config/rbac/role.yaml, docs/proxy.md, go.mod, go.sum, main.go, pkg/controllers/awsloadbalancercontroller/controller.go, pkg/controllers/awsloadbalancercontroller/deployment.go, pkg/controllers/awsloadbalancercontroller/deployment_test.go, pkg/controllers/suite_test.go, pkg/controllers/test/crd/credentialsrequest.yaml, pkg/controllers/watch_test.go, vendor/github.com/operator-framework/operator-lib/LICENSE, vendor/github.com/operator-framework/operator-lib/proxy/doc.go, vendor/github.com/operator-framework/operator-lib/proxy/proxy.go, vendor/modules.txt
- Propagate the proxy environment variables (`HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`) down to the controller.
- Add the custom trusted CA bundle to the controller: new volume and volume mount in the desired controller's deployment.
- Redeploy the controller if the custom CA bundle configmap changes: new watch for the CA bundle configmap in the operator, new annotation in the desired controller's deployment.
=> OCPBUGS-5295: egress proxy support for controller

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manifests/bases/aws-load-balancer-operator.clusterserviceversion.yaml
The documentation on released versions should be pinned to the specific version to avoid the instructions from the future releases.
=> docs: pin the prerequisite link to release-1.0

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manifests/bases/aws-load-balancer-operator.clusterserviceversion.yaml
This reverts commit 58596f0dfe9b7a29bfd5c6547f065e07178c565c. Wrong target branch for PR#102, should have been `release-1.0`, not `main`.
=> Revert "docs: pin the prerequisite link to release-1.0 (#102)"

OWNERS
Adding the whole NetworkEdge team as reviewers and approvers.
=> OWNERS: add NetworkEdge team

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manifests/bases/aws-load-balancer-operator.clusterserviceversion.yaml
The instructions for the STS mode come from the openshift docs now, not upstream.
=> OCPBUGS-14631: use openshift docs for operatorhub prerequsiste instructions

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manager/manager.yaml
This PR adds the aws-load-balancer-controller image containing the fix for the FIPS clusters whose maximum TLS version cannot be greater than 1.2.
The manual test can be found in the description of [the controller PR](https://github.com/openshift/aws-load-balancer-controller/pull/12).
=> OCPBUGS-14846: update the controller image to use TLS1.2 as minumum version for webhook server

test/e2e/operator_test.go, test/e2e/util.go
This PR adds basic tests for the load balancers of type NLB. The NLB support was rather prematurely [declared in the OpenShift docs](https://docs.openshift.com/container-platform/4.13/networking/aws_load_balancer_operator/understanding-aws-load-balancer-operator.html#nw-aws-load-balancer-operator_aws-load-balancer-operator) which resulted in some customers relying on it. The goal of this PR is to address this gap by validating that ALBO can work with service resources.
=> NE-1345: add e2e tests for NLB

Makefile, test/e2e/operator_test.go, test/e2e/util.go
Action items:
- Follow up of [a TODO in the e2e](https://github.com/openshift/aws-load-balancer-operator/blob/main/test/e2e/operator_test.go#L141-L142):
- Remove the copying of the credentials secret provisioned by the CI, ROSA can spawn 4.14 clusters now, so `STSIAMRoleARN` field is now available
- Follow-up of [a problem](https://github.com/openshift/aws-load-balancer-operator/pull/115#issuecomment-1783563662) found in the last PRs before the release:
- Create AWS Web ACLs as earlier as possible to save some time waiting for its availability. This helped to drop the test executing from ~800 seconds to ~500 seconds.
- Default e2e timeout is increased to `90m` as the time need for successful run is too close to the previous `60m` timeout.
=> OCPBUGS-22893: e2e- action items post 1.1 release

docs/install.md, docs/prerequisites.md
Replace `trusted policy` term with the correct [`trust policy`](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_terms-and-concepts.html#term_trust-policy). Follow-up of [a PR in the docs](https://github.com/openshift/openshift-docs/pull/67219#discussion_r1379837558).
=> NO-JIRA: Use trust policy term

Dockerfile, Makefile
This commit addresses all the errors detected by [the check-payload tool](https://github.com/openshift/check-payload) by implementing the following changes:
- Replaced the base image with a non-UBI variant.
- Updated the builder image to be FIPS-capable.
- Enabled dynamic linkage for the operator binary (`CGO_ENABLED=1`).
- Added the `strictfipsruntime` tag to the operator binary.
Additionally, implemented `image-fips-scan` command for local FIPS compliance checks.
Result:
```
$ IMG=quay.io/alebedev/albo make image-fips-scan
sudo podman run --privileged registry.ci.openshift.org/ci/check-payload:latest scan operator --spec quay.io/alebedev/albo
I0326 08:50:55.098182       1 main.go:302] using embedded config
...
I0326 08:50:55.098589       1 main.go:102] "scan" …
```
=> OCPBUGS-24653: Ensure FIPS compliance for operator image

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manager/manager.yaml
Use the latest controller image which is now FIPS compliant thanks to https://github.com/openshift/aws-load-balancer-controller/pull/21.
=> OCPBUGS-24653: bump FIPS compliant controller image

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manifests/bases/aws-load-balancer-operator.clusterserviceversion.yaml
According to the Red Hat Operator's [Best practices](https://docs.engineering.redhat.com/display/CFC/Best_Practices) the infrastructure annotations are now required. The [old "infrastructure-features" annotation is deprecated](https://github.com/openshift/openshift-docs/pull/69579) hence I removed it.
=> OCPBUGS-27023: add infrastructure annotations

Makefile, hack/controller/README.md, pkg/controllers/awsloadbalancercontroller/credentials_request.go
`hack/controller/` directory has 2 `CredentialsRequest` files. The goal of this PR is to explain why we need them both and where to use them.
=> OCPBUGS-36625: Add readme about controller's credentials requests

assets/iam-policy.json, bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, bundle/manifests/elbv2.k8s.aws_ingressclassparams.yaml, bundle/manifests/elbv2.k8s.aws_targetgroupbindings.yaml, config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml, config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml, config/manager/manager.yaml, config/rbac/upstream_role.yaml, hack/controller/controller-credentials-request.yaml, pkg/controllers/awsloadbalancercontroller/iam_policy.go, pkg/controllers/awsloadbalancercontroller/rbac_rules.go
- Updated controller image to the latest version from downstream.
- Re-generated operator bundle using `make bundle`, which also updated controller CRDs.
- Synced IAM policy with the latest downstream version.
- Re-generated managed IAM policy and credentials request using `make generate`.
- Updated managed controller RBAC to include permissions for leases.
- Note: Controller-runtime no longer supports ConfigMaps for leader election.
Integrates https://github.com/openshift/aws-load-balancer-controller/pull/23 into the operator.
=> NE-1808: Bump controller to v2.8.2

test/e2e/operator_test.go
WAF ACL may be create by one CI job but removed by another which may result into failed e2e test cases.
This commit adds Unix timestamp to WAF ACL names to minimize the occurrence of such situations.
=> NO-JIRA: e2e: Add unix timestamp to WAF ACL names to avoid conflicts

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manager/manager.yaml
Update the controller image reference in the operator manifests to the latest version available at quay.io/aws-load-balancer-operator/aws-load-balancer-controller. The previous image was pruned by quay.io and is no longer available for pull.
Related question in forum-ocp-testplatform: [link](https://redhat-internal.slack.com/archives/CBN38N3MW/p1749594215180509).
Quay.io question about pruning: [link](https://redhat-internal.slack.com/archives/C7WH69HCY/p1749594852800799).
=> NE-2064: Update controller image to latest available

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/manager/manager.yaml
This commit changes the strategy used to reference the controller image in the operator's deployment manifest. The `latest` floating tag is now used to avoid issues with older mirrored images being removed.
Since these manifests are used only in CI presubmits, there is no risk of breaking future releases, which will have pinned versions (SHA256 digests) for all images.
=> OCPBUGS-57339: Use floating tag for controller image

Containerfile.aws-load-balancer-operator
Use `test` builtin instead of `[]` to workaround
https://issues.redhat.com/browse/PSSECAUT-1207.
=> NE-2064: Use test bash builtin in Containerfile

bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml
This commit adds the `runAsNonRoot` field to the kube-rbac-proxy container in the operator deployment, preventing it from running as root and addressing the general Coverity warning: "The Kubernetes container is allowed to run as the root user."
=> NE-2064: Add runAsNonRoot to kube-rbac-proxy container

bundle-hack/bundle_vars.sh, bundle-hack/update_bundle.sh
If `VERSION` ends with `.0`, it represents the first release in a new minor channel. Such a release must not replace a version from a different minor channel. This behavior was already enforced by CPaaS bundle checks, so we now align with that rule here.
=> NE-2063: Prevent CSV replaces across minor channels

hack/controller/README.md, test/e2e/operator_test.go
AWS Load Balancer Controller CredentialsRequest is now created in the setup of the aws-load-balancer-operator e2e tests, eliminating the race condition where the target namespace for the request did not exist yet when the credentials request was created as part of the CI pre-install steps.
Example failure prior to this change:
> ```--- FAIL: TestAWSLoadBalancerControllerWithCredentialsSecret (920.10s) === RUN TestAWSLoadBalancerControllerWithCustomIngressClass operator_test.go:406: Creating test namespace "aws-load-balancer-test-custom-ing" operator_test.go:412: Creating a custom ingress class operator_test.go:422: Creating aws load balancer controller instance with custom ingress class util.go:72: failed to get deployment aws-load-balancer-controller-cluster: deployments.apps …
```
=> OCPBUGS-60009: Add AWS LB Controller CredentialsRequest in the e2e setup

Makefile, catalog/aws-load-balancer-operator/bundle.yaml
Switch `BUNDLE_IMG` to use the floating `latest` tag. This decouples bundle image updates from FBC updates when introducing a new bundle version.
Previously, bumping the bundle version caused `make catalog` to fail, since it attempted to pull a new tag that wasn’t yet merged. With this change, `make catalog` continues using the previous `latest` bundle image until the version bump is merged and `latest` is updated with the new contents.
=> NE-2123: Use latest tag for BUNDLE_IMG

bundle-hack/container_digest.sh
Fixing a typo introduced in https://github.com/openshift/aws-load-balancer-operator/pull/203.
=> NE-2123: Fix typo in operator image pullspec
